# Generated by Django 5.1 on 2024-09-03 19:08

import location.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="airport",
            name="image",
            field=models.ImageField(
                null=True, upload_to=location.models.airport_image_file_path
            ),
        ),
    ]
