# Generated by Django 5.1 on 2024-08-29 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="airplanetype",
            table="fleet_airplane_type",
        ),
    ]
