# Generated by Django 5.1 on 2024-09-02 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_ops", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="flights",
                to="flight_ops.route",
            ),
        ),
    ]
